### ISSUE TITLE
Trackpad zoom sensitivity

### ISSUE THREAD

**Issue by fxi** [GlobeletJS/GlobeletJS#17]
Interesting tool, thanks :)

**Describe the bug**
Using a trackpad, wheelZoom is extremely sensitive, the slightest move produce a huge zoom movement.

**How To Reproduce**
- Using a trackpad, zoom in, zoom out

**Expected behavior**
- Zoom steps that match maplibre, leaflet, etc..

**Screenshots**

![globelet_trackpad_sensitivity opt](https://user-images.githubusercontent.com/1196833/131565198-3d2fc25e-718c-49c5-90b3-5a8da8ab43e9.gif)

**Environment:**
 - Device:  MacBook pro
 - OS: macOS 10.5.2
 - Browser: Chrome 92, Firefox 89, Safari 14.1
 - GlobeletJS : 0.1.1

**Comment by jjhembd** [comment]
Thanks for the feedback, @fxi !

Zoom actions (and all other mouse/touch/trackpad interactions) are converted to camera motions in the [spinning-ball](https://github.com/GlobeletJS/spinning-ball) module. I opened an issue there to work on it, and test any solutions:
https://github.com/GlobeletJS/spinning-ball/issues/3

Are you familiar with how Leaflet handles zoom actions from different input devices?

**Comment by fxi** [comment]
I'm not familiar with that, but after a quick look I can see that [leaflet ](https://github.com/Leaflet/Leaflet/blob/0f904a515879fcd08f69b7f51799ee7f18f23fd8/src/map/handler/Map.ScrollWheelZoom.js#L62) seems to use a combination of debounce, zoom step by wheel event delta and a sigmoid function. mapbox-gl-js / [maplibre-gl-js](https://github.com/maplibre/maplibre-gl-js/blob/ba7bfbc846910c5ae848aaeebe4bde6833fc9cdc/src/ui/handler/scroll_zoom.js#L31) guesses if it's a trackpad and reduces the step size accordingly. It also enable fine zooming (v/4) if the shift key is pressed. For mouse wheels, an easing function is applied, and for trackpads, it looks like a more direct read.

**Comment by jjhembd** [comment]
Hi @fxi, I'm just getting back to this--I've spent the last few months adding rendering support for more style options.

The zoom handling is done in [touch-sampler](https://github.com/GlobeletJS/touch-sampler). I updated it to better handle different devices. Can you compare zooming on these two?
https://globeletjs.github.io/touch-sampler/examples/zoom-constant/
https://globeletjs.github.io/touch-sampler/examples/zoom-variable/

If I'm understanding the problem correctly, the first example ("zoom-constant") should zoom too fast on your device, and the second example ("zoom-variable") should behave more reasonably. But I can't confirm on my device (Surface Book 2) &mdash; I'm seeing identical behavior from both examples, on Chrome, Firefox, and Edge.

The new code borrows ideas from both [Leaflet](https://github.com/Leaflet/Leaflet/blob/911f578a608d71e0d67341fbfe871215ab30941d/src/dom/DomEvent.js#L257) and [d3-zoom](https://github.com/d3/d3-zoom/blob/1bccd3fd56ea24e9658bd7e7c24e9b89410c8967/src/zoom.js#L34)

**Comment by fxi** [comment]
Great !

Yes, the zoom-variable is much smoother and pleasant on my setup ( both Chrome 96, Safari 15 )

Nice work :) 


https://user-images.githubusercontent.com/1196833/146642210-36ec0fed-294a-4e2f-9810-741a74fe76ad.mov


https://user-images.githubusercontent.com/1196833/146642223-9dc02f46-2d1b-43c4-9b78-5e876528d51a.mov
